### ISSUE TITLE
MochiTextEncode - 'MochiT5Tokenizer' object has no attribute 't5xxl'

### ISSUE THREAD

**Issue by Said-Akbar** [kijai/ComfyUI-MochiWrapper#39]
HI,

I am getting the following error even though I installed all the requirement.txt packages:

# ComfyUI Error Report
## Error Details
- **Node Type:** MochiTextEncode
- **Exception Type:** AttributeError
- **Exception Message:** 'MochiT5Tokenizer' object has no attribute 't5xxl'
## Stack Trace
```
  File "/home/saidp/Downloads/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/saidp/Downloads/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/saidp/Downloads/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/saidp/Downloads/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/saidp/Downloads/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 318, in process
    clip.tokenizer.t5xxl.pad_to_max_length = True

```
## System Information
- **ComfyUI Version:** v0.2.4-12-g669d9e4
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25407520768
  - **VRAM Free:** 9378255060
  - **Torch VRAM Total:** 12415139840
  - **Torch VRAM Free:** 19779796

## Logs
```
2024-10-27 21:51:37,404 - root - INFO - Total VRAM 24230 MB, total RAM 96459 MB
2024-10-27 21:51:37,404 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-27 21:51:37,404 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-27 21:51:37,404 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-10-27 21:51:37,993 - root - INFO - Using pytorch cross attention
2024-10-27 21:51:38,572 - root - INFO - [Prompt Server] web root: /home/saidp/Downloads/ComfyUI/web
2024-10-27 21:51:38,842 - root - INFO - 
Import times for custom nodes:
2024-10-27 21:51:38,842 - root - INFO -    0.0 seconds: /home/saidp/Downloads/ComfyUI/custom_nodes/websocket_image_save.py
2024-10-27 21:51:38,842 - root - INFO -    0.1 seconds: /home/saidp/Downloads/ComfyUI/custom_nodes/ComfyUI-MochiWrapper
2024-10-27 21:51:38,842 - root - INFO - 
2024-10-27 21:51:38,845 - root - INFO - Starting server

2024-10-27 21:51:38,845 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-27 21:51:42,010 - root - INFO - got prompt
2024-10-27 21:51:42,015 - root - INFO - Initializing model...
2024-10-27 21:51:42,075 - root - INFO - Loading model state_dict from /home/saidp/Downloads/ComfyUI/models/diffusion_models/mochi/mochi_preview_dit_GGUF_Q8_0.safetensors...
2024-10-27 21:51:42,088 - root - INFO - Loading GGUF model state_dict...
2024-10-27 21:51:47,753 - root - ERROR - !!! Exception during processing !!! 'MochiT5Tokenizer' object has no attribute 't5xxl'
2024-10-27 21:51:47,754 - root - ERROR - Traceback (most recent call last):
  File "/home/saidp/Downloads/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/saidp/Downloads/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/saidp/Downloads/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/saidp/Downloads/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/saidp/Downloads/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 318, in process
    clip.tokenizer.t5xxl.pad_to_max_length = True
AttributeError: 'MochiT5Tokenizer' object has no attribute 't5xxl'

2024-10-27 21:51:47,754 - root - INFO - Prompt executed in 5.74 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":18,"nodes":[{"id":12,"type":"Note","pos":{"0":1271,"1":-119},"size":{"0":365.5867919921875,"1":208.3488311767578},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"title":"Note: WIP!","properties":{},"widgets_values":["VAE decoding is extremely heavy so tiling is necessary, I have not found best settings for it yet so testing help is appreciated, you can keep decoding after sampling as the latents are still in memory to see what works.\n\nEither adjust frame_batch_size to decode less frames at once, this tends to cause frame skipping though.\n\nOr use higher batch and smaller tiles to still fit it in memory."],"color":"#432","bgcolor":"#653"},{"id":10,"type":"MochiDecode","pos":{"0":1306,"1":158},"size":{"0":315,"1":222},"flags":{},"order":6,"mode":0,"inputs":[{"name":"vae","type":"MOCHIVAE","link":17},{"name":"samples","type":"LATENT","link":12}],"outputs":[{"name":"images","type":"IMAGE","links":[18],"slot_index":0}],"properties":{"Node name for S&R":"MochiDecode"},"widgets_values":[true,false,10,160,312,0.25,0.25]},{"id":15,"type":"SaveAnimatedWEBP","pos":{"0":1776,"1":175},"size":{"0":315,"1":154},"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":18}],"outputs":[],"properties":{},"widgets_values":["ComfyUI",6,true,80,"default"]},{"id":8,"type":"MochiTextEncode","pos":{"0":466,"1":605},"size":{"0":400,"1":200},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":8}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[9],"slot_index":0},{"name":"clip","type":"CLIP","links":null}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["",1,true]},{"id":1,"type":"MochiTextEncode","pos":{"0":484,"1":258},"size":{"0":413.45361328125,"1":268.5947265625},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":1}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[7],"slot_index":0},{"name":"clip","type":"CLIP","links":null}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["nature video of a red panda eating bamboo in front of a waterfall",1,true]},{"id":5,"type":"MochiSampler","pos":{"0":951,"1":217},"size":{"0":315,"1":286},"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","type":"MOCHIMODEL","link":16},{"name":"positive","type":"CONDITIONING","link":7},{"name":"negative","type":"CONDITIONING","link":9},{"name":"opt_sigmas","type":"SIGMAS","link":null,"shape":7}],"outputs":[{"name":"samples","type":"LATENT","links":[12],"slot_index":0}],"properties":{"Node name for S&R":"MochiSampler"},"widgets_values":[848,480,49,30,7,0,"fixed",0]},{"id":13,"type":"DownloadAndLoadMochiModel","pos":{"0":569,"1":15},"size":{"0":315,"1":174},"flags":{},"order":1,"mode":0,"inputs":[{"name":"trigger","type":"CONDITIONING","link":null,"shape":7},{"name":"compile_args","type":"MOCHICOMPILEARGS","link":null,"shape":7}],"outputs":[{"name":"mochi_model","type":"MOCHIMODEL","links":[16],"slot_index":0},{"name":"mochi_vae","type":"MOCHIVAE","links":[17],"slot_index":1}],"properties":{"Node name for S&R":"DownloadAndLoadMochiModel"},"widgets_values":["mochi_preview_dit_GGUF_Q8_0.safetensors","mochi_preview_vae_bf16.safetensors","fp16","sage_attn",false]},{"id":2,"type":"CLIPLoader","pos":{"0":-3,"1":462},"size":{"0":429.837646484375,"1":82},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[1,8]}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["mochi/t5xxl_fp16.safetensors","mochi"]}],"links":[[1,2,0,1,0,"CLIP"],[7,1,0,5,1,"CONDITIONING"],[8,2,0,8,0,"CLIP"],[9,8,0,5,2,"CONDITIONING"],[12,5,0,10,1,"LATENT"],[16,13,0,5,0,"MOCHIMODEL"],[17,13,1,10,0,"MOCHIVAE"],[18,10,0,15,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015781,"offset":[56.258011032557285,74.05782291617514]}},"version":0.4}
```

## Additional Context
I have t5xxl_fp16.safetensors in models/clip folder. This repo is in custom_nodes folder in ComfyUI.

Let me know if there is a fix. 

Thanks!

**Comment by kijai** [comment]
Added compatibility for the mochi type now, as well as ability to simply use the comfy CLIPTextEncode nodes as well.
