### ISSUE TITLE
import fail with err "No module named 'torch.nn.attention'"

### ISSUE THREAD

**Issue by czcz1024** [kijai/ComfyUI-MochiWrapper#40]
Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 15, in <module>
    from .mochi_preview.t2v_synth_mochi import T2VSynthMochiModel
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 54, in <module>
    from .dit.joint_model.asymm_models_joint import AsymmDiTJoint
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\dit\joint_model\asymm_models_joint.py", line 40, in <module>
    from torch.nn.attention import sdpa_kernel, SDPBackend
ModuleNotFoundError: No module named 'torch.nn.attention'

Cannot import D:\ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper module for custom nodes: No module named 'torch.nn.attention'

**Comment by kijai** [comment]
Torch version too old

**Comment by HWiese1980** [comment]
Which one do your nodes need?

**Comment by kijai** [comment]
> Which one do your nodes need?

Highly recommend the latest 2.5.1

**Comment by czcz1024** [comment]
> > Which one do your nodes need?
> 
> Highly recommend the latest 2.5.1

when i update torch to 2.5,i can't find a flash_attn whl for win10
do you know where can i download a pre compile whl for win10 torch2.5?

**Comment by kijai** [comment]
> > > Which one do your nodes need?
> > 
> > Highly recommend the latest 2.5.1
> 
> when i update torch to 2.5,i can't find a flash_attn whl for win10
> do you know where can i download a pre compile whl for win10 torch2.5?

You do not need flash attention for these nodes, or for anything else in comfy I can think of right now.
