### ISSUE TITLE
What's the implication of Mochi releasing the original decoder?

### ISSUE THREAD

**Issue by jpgallegoar** [kijai/ComfyUI-MochiWrapper#52]
I'm not too versed in ML, what can we now do that we previously couldn't?

**Comment by kijai** [comment]
Encoder is what they released now, decoder is what we already had. It allows doing video to video workflows.

**Comment by mikhail-shevtsov-wiregate** [comment]
@kijai Can you please share sample workflow on how to use Encoder?

**Comment by mikhail-shevtsov-wiregate** [comment]
@kijai Is this correct workflow?
![image](https://github.com/user-attachments/assets/d532ce7c-6874-4069-bf3b-dd648a099eb0)

Because when I try to start I'm getting an error: 
```
size mismatch for output_proj.weight: copying a param with shape torch.Size([3, 128]) from checkpoint, the shape in current model is torch.Size([24, 384])
```

**Comment by kijai** [comment]
Still figuring it out myself, for now you can get started with this:

![image](https://github.com/user-attachments/assets/5a9c2791-1c2d-48c5-900a-c6436497b6e1)

The encoder is a different model from the decoder, which was what the first VAE only was. You can get the bf16 version of the encoder from here:

https://huggingface.co/Kijai/Mochi_preview_comfy/blob/main/mochi_preview_vae_encoder_bf16_.safetensors

**Comment by 4lt3r3go** [comment]
```
!!! Exception during processing !!! object of type 'float' has no len()
Traceback (most recent call last):
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 512, in process
    latents = model.run(args)
              ^^^^^^^^^^^^^^^
  File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 241, in run
    len(cfg_schedule) == sample_steps
    ^^^^^^^^^^^^^^^^^
TypeError: object of type 'float' has no len()


```

![image](https://github.com/user-attachments/assets/ba4f85ee-84f3-4317-b8b4-0dda64bade34)

**Comment by kijai** [comment]
> ```
> !!! Exception during processing !!! object of type 'float' has no len()
> Traceback (most recent call last):
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 512, in process
>     latents = model.run(args)
>               ^^^^^^^^^^^^^^^
>   File "F:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 241, in run
>     len(cfg_schedule) == sample_steps
>     ^^^^^^^^^^^^^^^^^
> TypeError: object of type 'float' has no len()
> 
> 
> ```
> 
> 
> 
> 

I think you need to remake that sampler node as it looks wrong, there are more inputs now so old workflows need updating.

**Comment by 4lt3r3go** [comment]
![image](https://github.com/user-attachments/assets/662c5ccd-a5db-4d7d-bf0c-e4130781f854)
 i thought that and rebulided with new nodes ty
 but i keep gettin the error

**Comment by kijai** [comment]
Have you refreshed your browser? The cfg_schedule is supposed to be an input, not widget:

![image](https://github.com/user-attachments/assets/4958ddd3-9481-4cf3-a314-9d31dd153f4c)

**Comment by 4lt3r3go** [comment]
yeah thats what i supposed to be the problem but looks bugged or something
look 
![image](https://github.com/user-attachments/assets/384eb243-e6e2-4728-8a60-f9b30ca8c4f2)

**Comment by 4lt3r3go** [comment]
ok now magically solved after restart  again.

**Comment by kijai** [comment]
> yeah thats what i supposed to be the problem but looks bugged or something
> look 
> ![image](https://github.com/user-attachments/assets/384eb243-e6e2-4728-8a60-f9b30ca8c4f2)
> 

Restart and refresh the browser, then recreate the node.

**Comment by 4lt3r3go** [comment]
OK O GOT THIS.
  
![image](https://github.com/user-attachments/assets/819025ba-e3d5-4c44-8a89-4071db4347fa)

experimenting with this sigmas. looks like higher sigma steps value gives better results
trying to understand if theres some sort of denoise level to change

**Comment by kijai** [comment]
> OK I GOT THIS.
> 
> experimenting with this sigmas. looks like higher sigma steps value gives better results trying to understand if theres some sort of denoise level to change

Denoise is what affects the sigmas, but yeah it may be simpler to use it like that, so I added it as option to the node:

![image](https://github.com/user-attachments/assets/9b75e054-d289-4105-b284-2ef1d1e72e8f)

**Comment by 4lt3r3go** [comment]
woah that was so fast! beautiful!
now i wonder if there's a way to trick this and make it work as a IMAGE to video, providing only the first frame and then only latent so mochi can continue

**Comment by 4lt3r3go** [comment]
![image](https://github.com/user-attachments/assets/7b6c29c7-4ae7-43d2-aca0-45ecfa79697a)
 i tryed to use this and got a psycadelic result. nope😁
 i think this need some different approach to make Image to Video works

**Comment by jpgallegoar** [comment]
image to video needs a specific model finetuned for it

**Comment by 4lt3r3go** [comment]
> image to video needs a specific model finetuned for it

I can imagin ... i just desperately want it so much that i tryed everything achieve something even remotely similar to I2V😁
