### ISSUE TITLE
vae encoder has a problem

### ISSUE THREAD

**Issue by mikeyimer** [kijai/ComfyUI-MochiWrapper#61]
# ComfyUI Error Report
## Error Details
- **Node Type:** MochiVAEEncoderLoader
- **Exception Type:** KeyError
- **Exception Message:** 'layers.0.weight'
## Stack Trace
```
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 380, in loadmodel
    set_module_tensor_to_device(encoder, name, dtype=dtype, device=offload_device, value=encoder_sd[name])

```
## System Information
- **ComfyUI Version:** v0.2.2-50-g0bfc7cc
- **Arguments:** main.py --port=6006
- **OS:** posix
- **Python Version:** 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA A100-PCIE-40GB : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 42285268992
  - **VRAM Free:** 20315287860
  - **Torch VRAM Total:** 21508390912
  - **Torch VRAM Free:** 2928948

## Logs
```
2024-11-04 18:07:41,347 - root - INFO - Total VRAM 40326 MB, total RAM 644982 MB
2024-11-04 18:07:41,347 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-04 18:07:42,742 - root - INFO - xformers version: 0.0.27
2024-11-04 18:07:42,743 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-04 18:07:42,743 - root - INFO - Device: cuda:0 NVIDIA A100-PCIE-40GB : cudaMallocAsync
2024-11-04 18:07:42,868 - root - INFO - Using xformers cross attention
2024-11-04 18:07:43,565 - root - INFO - [Prompt Server] web root: /root/autodl-tmp/ComfyUI/web
2024-11-04 18:07:44,710 - root - INFO - Total VRAM 40326 MB, total RAM 644982 MB
2024-11-04 18:07:44,711 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-04 18:07:44,711 - root - INFO - xformers version: 0.0.27
2024-11-04 18:07:44,711 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-04 18:07:44,711 - root - INFO - Device: cuda:0 NVIDIA A100-PCIE-40GB : cudaMallocAsync
2024-11-04 18:07:47,429 - root - INFO - 
Import times for custom nodes:
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-mxToolkit
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
2024-11-04 18:07:47,429 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiEdit
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-ToolBox
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-IC-Light
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-AnimateDiff
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Crystools
2024-11-04 18:07:47,430 - root - INFO -    0.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-04 18:07:47,430 - root - INFO -    0.1 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/comfyui-reactor-node
2024-11-04 18:07:47,430 - root - INFO -    0.2 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-11-04 18:07:47,430 - root - INFO -    0.2 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI_InstantID
2024-11-04 18:07:47,430 - root - INFO -    0.3 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/rgthree-comfy
2024-11-04 18:07:47,430 - root - INFO -    0.4 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-11-04 18:07:47,430 - root - INFO -    0.5 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper
2024-11-04 18:07:47,430 - root - INFO -    0.7 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-FluxTrainer
2024-11-04 18:07:47,430 - root - INFO -    1.0 seconds: /root/autodl-tmp/ComfyUI/custom_nodes/was-node-suite-comfyui
2024-11-04 18:07:47,430 - root - INFO - 
2024-11-04 18:07:47,443 - root - INFO - Starting server

2024-11-04 18:07:47,443 - root - INFO - To see the GUI go to: http://127.0.0.1:6006
2024-11-04 18:07:59,143 - root - INFO - got prompt
2024-11-04 18:07:59,169 - root - INFO - Initializing model...
2024-11-04 18:07:59,264 - root - INFO - Loading model state_dict from /root/autodl-tmp/ComfyUI/models/diffusion_models/mochi/mochi_preview_dit_bf16.safetensors...
2024-11-04 18:07:59,312 - root - INFO - Using accelerate to load and assign model weights to device...
2024-11-04 18:08:09,625 - root - ERROR - !!! Exception during processing !!! 'layers.0.weight'
2024-11-04 18:08:09,626 - root - ERROR - Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 380, in loadmodel
    set_module_tensor_to_device(encoder, name, dtype=dtype, device=offload_device, value=encoder_sd[name])
KeyError: 'layers.0.weight'

2024-11-04 18:08:09,626 - root - INFO - Prompt executed in 10.47 seconds
2024-11-04 18:08:18,632 - root - INFO - got prompt
2024-11-04 18:08:18,677 - root - ERROR - !!! Exception during processing !!! 'layers.0.weight'
2024-11-04 18:08:18,678 - root - ERROR - Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 380, in loadmodel
    set_module_tensor_to_device(encoder, name, dtype=dtype, device=offload_device, value=encoder_sd[name])
KeyError: 'layers.0.weight'

2024-11-04 18:08:18,678 - root - INFO - Prompt executed in 0.03 seconds
2024-11-04 18:08:48,272 - root - INFO - got prompt
2024-11-04 18:08:48,318 - root - ERROR - !!! Exception during processing !!! 'layers.0.weight'
2024-11-04 18:08:48,318 - root - ERROR - Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 380, in loadmodel
    set_module_tensor_to_device(encoder, name, dtype=dtype, device=offload_device, value=encoder_sd[name])
KeyError: 'layers.0.weight'

2024-11-04 18:08:48,318 - root - INFO - Prompt executed in 0.03 seconds
2024-11-04 18:09:03,102 - root - INFO - got prompt
2024-11-04 18:09:03,148 - root - ERROR - !!! Exception during processing !!! 'layers.0.weight'
2024-11-04 18:09:03,149 - root - ERROR - Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 380, in loadmodel
    set_module_tensor_to_device(encoder, name, dtype=dtype, device=offload_device, value=encoder_sd[name])
KeyError: 'layers.0.weight'

2024-11-04 18:09:03,149 - root - INFO - Prompt executed in 0.03 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":63,"last_link_id":103,"nodes":[{"id":22,"type":"MochiImageEncode","pos":{"0":431,"1":542},"size":{"0":210,"1":174},"flags":{},"order":13,"mode":0,"inputs":[{"name":"encoder","type":"MOCHIVAE","link":36,"label":"encoder"},{"name":"images","type":"IMAGE","link":33,"label":"images"}],"outputs":[{"name":"samples","type":"LATENT","links":[78,84],"slot_index":0,"label":"samples"}],"properties":{"Node name for S&R":"MochiImageEncode"},"widgets_values":[false,4,4,16,1]},{"id":24,"type":"ImageScale","pos":{"0":435,"1":771},"size":{"0":210,"1":130},"flags":{},"order":11,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":32,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[33],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"ImageScale"},"widgets_values":["nearest-exact",848,480,"disabled"]},{"id":46,"type":"MochiWrapperSamplerCustom","pos":{"0":1223.683349609375,"1":-130},"size":{"0":252.70352172851562,"1":230},"flags":{},"order":16,"mode":0,"inputs":[{"name":"model","type":"MOCHIMODEL","link":72,"label":"model"},{"name":"positive","type":"CONDITIONING","link":73,"label":"positive"},{"name":"negative","type":"CONDITIONING","link":74,"label":"negative"},{"name":"sigmas","type":"SIGMAS","link":93,"label":"sigmas"},{"name":"latents","type":"LATENT","link":86,"label":"latents"},{"name":"sampler","type":"SAMPLER","link":79,"label":"sampler"}],"outputs":[{"name":"samples","type":"LATENT","links":[94],"slot_index":0,"label":"samples"}],"properties":{"Node name for S&R":"MochiWrapperSamplerCustom"},"widgets_values":[4.5,0,"fixed",false]},{"id":51,"type":"MochiPrepareSigmas","pos":{"0":1259.683349609375,"1":152},"size":{"0":195.5120391845703,"1":26},"flags":{},"order":8,"mode":0,"inputs":[{"name":"sigmas","type":"SIGMAS","link":92,"label":"sigmas"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[93],"slot_index":0,"label":"SIGMAS"}],"properties":{"Node name for S&R":"MochiPrepareSigmas"}},{"id":9,"type":"VHS_VideoCombine","pos":{"0":2040,"1":143},"size":[1261.0787353515625,310],"flags":{},"order":18,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":24,"label":"图像"},{"name":"audio","type":"AUDIO","link":null,"shape":7,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7,"label":"批次管理"},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"Mochi_preview","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":false,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"Mochi_preview_00043.mp4","subfolder":"","type":"temp","format":"video/h264-mp4","frame_rate":24},"muted":false}}},{"id":15,"type":"MochiDecodeSpatialTiling","pos":{"0":1576,"1":82},"size":{"0":260.3999938964844,"1":198},"flags":{},"order":17,"mode":0,"inputs":[{"name":"vae","type":"MOCHIVAE","link":23,"label":"vae"},{"name":"samples","type":"LATENT","link":94,"label":"samples"}],"outputs":[{"name":"images","type":"IMAGE","links":[24],"slot_index":0,"label":"images"}],"properties":{"Node name for S&R":"MochiDecodeSpatialTiling"},"widgets_values":[true,4,4,16,1,6]},{"id":48,"type":"MochiWrapperSamplerCustom","pos":{"0":844,"1":169},"size":{"0":243.60000610351562,"1":230},"flags":{},"order":15,"mode":0,"inputs":[{"name":"model","type":"MOCHIMODEL","link":81,"label":"model"},{"name":"positive","type":"CONDITIONING","link":82,"label":"positive"},{"name":"negative","type":"CONDITIONING","link":83,"label":"negative"},{"name":"sigmas","type":"SIGMAS","link":85,"label":"sigmas"},{"name":"latents","type":"LATENT","link":84,"label":"latents"},{"name":"sampler","type":"SAMPLER","link":87,"label":"sampler"}],"outputs":[{"name":"samples","type":"LATENT","links":[86],"slot_index":0,"label":"samples"}],"properties":{"Node name for S&R":"MochiWrapperSamplerCustom"},"widgets_values":[1,1,"fixed",false]},{"id":30,"type":"FlipSigmas","pos":{"0":893,"1":446},"size":{"0":145.175537109375,"1":26},"flags":{},"order":12,"mode":0,"inputs":[{"name":"sigmas","type":"SIGMAS","link":91,"label":"Sigmas"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[85],"slot_index":0,"label":"Sigmas"}],"properties":{"Node name for S&R":"FlipSigmas"}},{"id":50,"type":"MochiPrepareSigmas","pos":{"0":876,"1":526},"size":{"0":172.05398559570312,"1":26},"flags":{},"order":7,"mode":0,"inputs":[{"name":"sigmas","type":"SIGMAS","link":90,"label":"sigmas"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[91],"slot_index":0,"label":"SIGMAS"}],"properties":{"Node name for S&R":"MochiPrepareSigmas"}},{"id":49,"type":"MochiUnsampler","pos":{"0":855,"1":760},"size":{"0":210,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[87],"slot_index":0,"label":"SAMPLER"}],"properties":{"Node name for S&R":"MochiUnsampler"},"widgets_values":[0,"fixed",0]},{"id":21,"type":"MochiSigmaSchedule","pos":{"0":854,"1":603},"size":{"0":210,"1":130},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"sigmas","type":"SIGMAS","links":[90],"slot_index":0,"label":"sigmas"}],"properties":{"Node name for S&R":"MochiSigmaSchedule"},"widgets_values":[50,0.025,15,1]},{"id":47,"type":"MochiResampler","pos":{"0":1237.683349609375,"1":404},"size":{"0":210,"1":130},"flags":{},"order":14,"mode":0,"inputs":[{"name":"latents","type":"LATENT","link":78,"label":"latents"}],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[79],"slot_index":0,"label":"SAMPLER"}],"properties":{"Node name for S&R":"MochiResampler"},"widgets_values":[0.8,5,20,"linear_decrease"]},{"id":33,"type":"MochiSigmaSchedule","pos":{"0":1236.683349609375,"1":247},"size":{"0":210,"1":130},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"sigmas","type":"SIGMAS","links":[92],"slot_index":0,"label":"sigmas"}],"properties":{"Node name for S&R":"MochiSigmaSchedule"},"widgets_values":[50,0.025,15,1]},{"id":8,"type":"MochiTextEncode","pos":{"0":439,"1":442},"size":{"0":379.5408020019531,"1":144},"flags":{"collapsed":true},"order":10,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":69,"label":"clip"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[74,82,83],"slot_index":0,"label":"conditioning"},{"name":"clip","type":"CLIP","links":null,"label":"clip"}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["",1,true]},{"id":2,"type":"CLIPLoader","pos":{"0":19,"1":179},"size":{"0":210,"1":82},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[1,69],"slot_index":0,"label":"CLIP"}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp16.safetensors","sd3"]},{"id":27,"type":"MochiVAEEncoderLoader","pos":{"0":-2,"1":531},"size":{"0":236.8000030517578,"1":82},"flags":{},"order":4,"mode":0,"inputs":[{"name":"torch_compile_args","type":"MOCHICOMPILEARGS","link":null,"shape":7,"label":"torch_compile_args"}],"outputs":[{"name":"mochi_vae","type":"MOCHIVAE","links":[36],"slot_index":0,"label":"mochi_vae"}],"properties":{"Node name for S&R":"MochiVAEEncoderLoader"},"widgets_values":["mochi/mochi_preview_vae_decoder_bf16.safetensors","bf16"]},{"id":1,"type":"MochiTextEncode","pos":{"0":297,"1":152},"size":{"0":380.0573425292969,"1":184.70144653320312},"flags":{},"order":9,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":1,"label":"clip"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[73],"slot_index":0,"label":"conditioning"},{"name":"clip","type":"CLIP","links":[],"slot_index":1,"label":"clip"}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["Wonder Woman, adorned in her iconic red, blue, and gold armor, gracefully dances in a lush, moonlit forest. Her silver tiara glints under the soft glow of the moon, and her golden lasso swirls around her as she moves with fluid elegance. ",1,true]},{"id":4,"type":"DownloadAndLoadMochiModel","pos":{"0":275,"1":-123},"size":{"0":364.4028015136719,"1":174},"flags":{},"order":5,"mode":0,"inputs":[{"name":"trigger","type":"CONDITIONING","link":null,"shape":7,"label":"trigger"},{"name":"compile_args","type":"MOCHICOMPILEARGS","link":null,"shape":7,"label":"compile_args"}],"outputs":[{"name":"mochi_model","type":"MOCHIMODEL","links":[72,81],"slot_index":0,"label":"mochi_model"},{"name":"mochi_vae","type":"MOCHIVAE","links":[23],"slot_index":1,"label":"mochi_vae"}],"properties":{"Node name for S&R":"DownloadAndLoadMochiModel"},"widgets_values":["mochi_preview_dit_bf16.safetensors","mochi_preview_vae_decoder_bf16.safetensors","fp16","sdpa",false]},{"id":23,"type":"VHS_LoadVideo","pos":{"0":-138,"1":781},"size":[252.056640625,508.056640625],"flags":{},"order":6,"mode":0,"inputs":[{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7,"label":"批次管理"},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[32],"slot_index":0,"label":"图像"},{"name":"frame_count","type":"INT","links":null,"label":"帧计数"},{"name":"audio","type":"AUDIO","links":null,"label":"音频"},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"label":"视频信息"}],"properties":{"Node name for S&R":"VHS_LoadVideo"},"widgets_values":{"video":"6月15日 (1).mp4","force_rate":0,"force_size":"Disabled","custom_width":512,"custom_height":512,"frame_load_cap":13,"skip_first_frames":0,"select_every_nth":1,"choose video to upload":"image","videopreview":{"hidden":false,"paused":false,"params":{"force_rate":0,"frame_load_cap":13,"skip_first_frames":0,"select_every_nth":1,"filename":"6月15日 (1).mp4","type":"input","format":"video/mp4"},"muted":false}}}],"links":[[1,2,0,1,0,"CLIP"],[23,4,1,15,0,"MOCHIVAE"],[24,15,0,9,0,"IMAGE"],[32,23,0,24,0,"IMAGE"],[33,24,0,22,1,"IMAGE"],[36,27,0,22,0,"MOCHIVAE"],[69,2,0,8,0,"CLIP"],[72,4,0,46,0,"MOCHIMODEL"],[73,1,0,46,1,"CONDITIONING"],[74,8,0,46,2,"CONDITIONING"],[78,22,0,47,0,"LATENT"],[79,47,0,46,5,"SAMPLER"],[81,4,0,48,0,"MOCHIMODEL"],[82,8,0,48,1,"CONDITIONING"],[83,8,0,48,2,"CONDITIONING"],[84,22,0,48,4,"LATENT"],[85,30,0,48,3,"SIGMAS"],[86,48,0,46,4,"LATENT"],[87,49,0,48,5,"SAMPLER"],[90,21,0,50,0,"SIGMAS"],[91,50,0,30,0,"SIGMAS"],[92,33,0,51,0,"SIGMAS"],[93,51,0,46,3,"SIGMAS"],[94,46,0,15,1,"LATENT"]],"groups":[{"title":"Unsampling","bounding":[834,95,264,805],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Sampling","bounding":[1214,-204,273,748],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.9090909090909091,"offset":[144.24470323065376,252.71314800901558]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
![图片](https://github.com/user-attachments/assets/fd1a0599-036e-4e7e-883f-cf34da6cebce)

**Comment by kijai** [comment]
Are you trying to load the actual encoder file though? It's not the same as the initial VAE released, which was decoder only.

**Comment by mosefi85** [comment]
hi , I have same problem how can i fix that? thank you
