### ISSUE TITLE
Mochi Model Loader doesn't work but down(load) does, because of vae_stats_path

### ISSUE THREAD

**Issue by cchance27** [kijai/ComfyUI-MochiWrapper#63]
When loading the Q4 v2 safetensor in the loader node, i get the following, but it loads fine if i use the down(load) node for the model loader instead.

```
ERROR:root:!!! Exception during processing !!! T2VSynthMochiModel.__init__() got an unexpected keyword argument 'vae_stats_path'
!!! Exception during processing !!! T2VSynthMochiModel.__init__() got an unexpected keyword argument 'vae_stats_path'
ERROR:root:Traceback (most recent call last):
  File "/Volumes/2TB/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/2TB/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/2TB/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Volumes/2TB/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/2TB/AI/ComfyUI/custom_nodes/ComfyUI-MochiWrapper/nodes.py", line 223, in loadmodel
    model = T2VSynthMochiModel(
            ^^^^^^^^^^^^^^^^^^^
TypeError: T2VSynthMochiModel.__init__() got an unexpected keyword argument 'vae_stats_path'
```

**Comment by kijai** [comment]
Missed that, thanks, fixed.
