### ISSUE TITLE
Missing Node Types

### ISSUE THREAD

**Issue by hosseinbehrad** [kijai/ComfyUI-MochiWrapper#89]
I installed by git cloning the repo into custom_nodes
after install and load your wrokflow 

![image](https://github.com/user-attachments/assets/6d6fc8aa-0a3a-4332-99ae-e4f352288f12)

please help me

i can't find ComfyUI-MochiWrapper nods

**Comment by jepjoo** [comment]
Should install fine from ComfyUI Manager menu -> "Install via Git URL"

**Comment by hosseinbehrad** [comment]
I tried this before and I get this error

![image](https://github.com/user-attachments/assets/7374cc65-a09e-4da6-9f28-b9171dd0376c)
#

**Comment by hosseinbehrad** [comment]
I tried this before and I get this error

![image](https://github.com/user-attachments/assets/692d3c15-1289-436b-893c-15e92f6e95fb)

**Comment by hosseinbehrad** [comment]
I solved the security problem and installed it through "Install via Git URL", but I still got the "Missing Node Types" error

**Comment by kijai** [comment]
You probably need to update your torch version, the manager will never do that for you. Torch 2.5.1 is highly recommended and it's what ComfyUI itself comes with now.

**Comment by hosseinbehrad** [comment]
I also updated the torch, but unfortunately my problem was not solved

![image](https://github.com/user-attachments/assets/2571bde2-c4f2-4944-a49c-e2c0b50330cb)

**Comment by kijai** [comment]
> I also updated the torch, but unfortunately my problem was not solved
> 
> ![image](https://private-user-images.githubusercontent.com/132351642/385345005-2571bde2-c4f2-4944-a49c-e2c0b50330cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjU2MDIsIm5iZiI6MTczMTQyNTMwMiwicGF0aCI6Ii8xMzIzNTE2NDIvMzg1MzQ1MDA1LTI1NzFiZGUyLWM0ZjItNDk0NC1hNDljLWUyYzBiNTAzMzBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNTI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmRhMjc4NGJmYzM2YjBiYzlkZjc2ZGRmZjIyMjAyZTU2MGQ3YWU1YTY3ZDY3ODRlYmY3ZTNhZWViNjQ1N2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LSp7VDIckwg7Nz77JzlB8quHAuBGg03m4UjV03xbJUc)

Then please show the whole startup log to see what is failing to import, only other thing besides that these nodes use should be `accelerate`

**Comment by hosseinbehrad** [comment]
> > I also updated the torch, but unfortunately my problem was not solved
> > ![image](https://private-user-images.githubusercontent.com/132351642/385345005-2571bde2-c4f2-4944-a49c-e2c0b50330cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjU2MDIsIm5iZiI6MTczMTQyNTMwMiwicGF0aCI6Ii8xMzIzNTE2NDIvMzg1MzQ1MDA1LTI1NzFiZGUyLWM0ZjItNDk0NC1hNDljLWUyYzBiNTAzMzBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxNTI4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmRhMjc4NGJmYzM2YjBiYzlkZjc2ZGRmZjIyMjAyZTU2MGQ3YWU1YTY3ZDY3ODRlYmY3ZTNhZWViNjQ1N2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LSp7VDIckwg7Nz77JzlB8quHAuBGg03m4UjV03xbJUc)
> 
> Then please show the whole startup log to see what is failing to import, only other thing besides that these nodes use should be `accelerate`

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
[ERROR] An error occurred while retrieving information for the 'controlaux_hed' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_midas' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_mlsd' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_openpose' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_pidi' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_dwpose' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_normal_bae' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart_anime' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_zoe' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_sam' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_leres' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_canny' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_content' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_face_detector' node.
Traceback (most recent call last):
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
                                     ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'keys'

QualityOfLifeSuit_Omar92::NSP ready
[]
[]

**Comment by kijai** [comment]
The import error would be way before all that, those errors have nothing to do with this.

**Comment by hosseinbehrad** [comment]
File "E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 12, in <module>
    from .mochi_preview.t2v_synth_mochi import T2VSynthMochiModel
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 52, in <module>
    from .dit.joint_model.asymm_models_joint import AsymmDiTJoint
  File "E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\dit\joint_model\asymm_models_joint.py", line 31, in <module>
    from torch.nn.attention import sdpa_kernel, SDPBackend
ModuleNotFoundError: No module named 'torch.nn.attention'

Cannot import E:\Ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper module for custom nodes: No module named 'torch.nn.attention'
←[0m←[1;34m[SD Prompt Reader] ←[36mNode version: 1.3.4←[0m
←[0m←[1;34m[SD Prompt Reader] ←[36mCore version: 1.3.5←[0m
Traceback (most recent call last):

**Comment by kijai** [comment]
`ModuleNotFoundError: No module named 'torch.nn.attention'` this would imply you do not have torch 2.5.1 in the python environment you are running comfy in.

**Comment by kijai** [comment]
As you are running portable you need to update the portable python environment, you have torch 2.5.1 only in your system wide python environment. The portable has update scripts in it's update folder that should take care of it.

**Comment by hosseinbehrad** [comment]
I installed it here: E:\Ai\ComfyUI_windows_portable\python_embeded\Lib\site-packages

 Did I install it in the wrong place? Where should I install it?

**Comment by kijai** [comment]
Use the python.exe in the python_embeded folder to install stuff for portable, you can check the torch version by running it like this in that folder:

`python.exe -m pip show torch`

Similarly to update:

`python.exe -m pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124`

**Comment by hosseinbehrad** [comment]
Thank you for taking the time to guide me
I am a newbie
Thank you very much
I am updating the torch
If I had a problem, I would disturb you

**Comment by GuaishouDM1** [comment]
Hello, Kijai! I am also encountered this broblem. I updated my torch, following your guide, but nothing seems to work. The comfyui cannot load this extension. "0.3 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main"

**Comment by kijai** [comment]
> Hello, Kijai! I am also encountered this broblem. I updated my torch, following your guide, but nothing seems to work. The comfyui cannot load this extension. "0.3 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main"

Need to see the whole error.

**Comment by GuaishouDM1** [comment]
> > Hello, Kijai! I am also encountered this broblem. I updated my torch, following your guide, but nothing seems to work. The comfyui cannot load this extension. "0.3 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main"
> 
> Need to see the whole error.

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main\nodes.py", line 12, in <module>
    from .mochi_preview.t2v_synth_mochi import T2VSynthMochiModel
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main\mochi_preview\t2v_synth_mochi.py", line 52, in <module>
    from .dit.joint_model.asymm_models_joint import AsymmDiTJoint
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main\mochi_preview\dit\joint_model\asymm_models_joint.py", line 31, in <module>
    from torch.nn.attention import sdpa_kernel, SDPBackend
ModuleNotFoundError: No module named 'torch.nn.attention'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper-main module for custom nodes: No module named 'torch.nn.attention'

This what I get at the start.
I Updated torch in comfyui folder, the package versions: 

D:\ComfyUI_windows_portable\ComfyUI>pip freeze | findstr torch
open-clip-torch==2.22.0
pytorch-lightning==1.9.3
torch==2.5.1+cu124
torchaudio==2.5.1+cu124
torchmetrics==1.4.0.post0
torchvision==0.20.1+cu124

**Comment by GuaishouDM1** [comment]
Hello once again. Im so apologize for being dumb. I executed your command in python_embedded folder and everything started properly.

**Comment by Kallamamran** [comment]
Updated torch to 2.5.1 and now it seem to be working
![image](https://github.com/user-attachments/assets/1906c109-7907-424e-82af-52d0a1ca126d)
but... Still no bueno...


```
Initializing model...
Loading model state_dict from Q:\ComfyUI\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
Using accelerate to load and assign model weights to device...
clip missing: ['text_projection.weight']
!!! Exception during processing !!! 'attention_mask'
Traceback (most recent call last):
  File "Q:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "Q:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "Q:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "Q:\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 471, in process
    "attention_mask": attention_mask["attention_mask"].bool(),
KeyError: 'attention_mask'

Prompt executed in 4.89 seconds
```

**Comment by kijai** [comment]
> Updated torch to 2.5.1 and now it seem to be working ![image](https://private-user-images.githubusercontent.com/25354644/390424078-1906c109-7907-424e-82af-52d0a1ca126d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTUyMTgsIm5iZiI6MTczMjcxNDkxOCwicGF0aCI6Ii8yNTM1NDY0NC8zOTA0MjQwNzgtMTkwNmMxMDktNzkwNy00MjRlLTgyYWYtNTJkMGExY2ExMjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEzNDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZGNhN2UzMGNmZDI5NDQzMTQwNjBlMGJhYmYzZWQxZGFmMDk4NDM4MjFkZmFmYTdjMWM0MGNjMTczMzRmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YO8fZ9aVv96VD91AB2CkX3_l8giFPMmDkaFEB0Iabgo) but... Still no bueno...
> 
> ```
> Initializing model...
> Loading model state_dict from Q:\ComfyUI\models\diffusion_models\mochi\mochi_preview_dit_fp8_e4m3fn.safetensors...
> Using accelerate to load and assign model weights to device...
> clip missing: ['text_projection.weight']
> !!! Exception during processing !!! 'attention_mask'
> Traceback (most recent call last):
>   File "Q:\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "Q:\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "Q:\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "Q:\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>   File "Q:\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 471, in process
>     "attention_mask": attention_mask["attention_mask"].bool(),
> KeyError: 'attention_mask'
> 
> Prompt executed in 4.89 seconds
> ```

Seems to fail at the text encoding, is your ComfyUI itself up to date?

**Comment by vladislav-vitalyevich-panin** [comment]
Also, the description does not mention it, but it seems that for provided example workflows ComfyUI-VideoHelperSuite is required, because the node "VHS_VideoCombine" seems to originate there.

**Comment by Bartabok** [comment]
> As you are running portable you need to update the portable python environment, you have torch 2.5.1 only in your system wide python environment. The portable has update scripts in it's update folder that should take care of it.

....and the light came from heaven and I was enlightened !
*Gregorian chants*

:D
Thanks a lot kijai !! I wasted hours trying to solve a problem while uninstalling, reinstalling stuff for nothing :D everything is clearer now
